# Generated by Django 5.2 on 2026-03-09 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SARVesselDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='SAR scene acquisition date')),
                ('vessel_count', models.IntegerField(help_text='Ships detected in chokepoint bbox')),
                ('baseline_count', models.FloatField(blank=True, help_text='Pre-war daily average vessel count', null=True)),
                ('pct_change', models.FloatField(blank=True, help_text='Percentage change vs baseline', null=True)),
                ('scene_id', models.CharField(help_text='Sentinel-1 granule ID', max_length=200)),
                ('scene_coverage', models.FloatField(default=0, help_text='Fraction of chokepoint bbox covered by valid SAR data')),
                ('mean_scr_db', models.FloatField(default=0, help_text='Mean ship-to-clutter ratio of detections (dB)')),
                ('polarization', models.CharField(default='VV', max_length=5)),
                ('chokepoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sar_vessel_detections', to='pipeline.areaofinterest')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('chokepoint', 'date')},
            },
        ),
    ]
