# Generated by Django 5.2 on 2026-03-10 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_sarvesseldetection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofinterest',
            name='category',
            field=models.CharField(choices=[('city', 'City'), ('infrastructure', 'Critical Infrastructure'), ('agriculture', 'Agricultural Region'), ('chokepoint', 'Maritime Chokepoint'), ('port', 'Port'), ('marina', 'Marina'), ('airport', 'Airport'), ('approach', 'Maritime Approach')], max_length=50),
        ),
        migrations.CreateModel(
            name='MigrationPressureIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('marina_score', models.FloatField(default=0, help_text='Normalised marina vessel count delta (0–1)')),
                ('airport_score', models.FloatField(default=0, help_text='Normalised airport aircraft count delta (0–1)')),
                ('nightlight_score', models.FloatField(default=0, help_text='Normalised nightlight activity change (0–1)')),
                ('sar_vessel_score', models.FloatField(default=0, help_text='SAR-detected vessel count in approach zones (0–1)')),
                ('gulf_push_score', models.FloatField(default=0, help_text='Inverse of Gulf compound risk — higher = more push factor (0–1)')),
                ('migration_pressure', models.FloatField(default=0, help_text='Weighted composite migration pressure score (0–1)')),
                ('pressure_level', models.CharField(choices=[('baseline', 'Baseline'), ('elevated', 'Elevated'), ('high', 'High'), ('surge', 'Surge')], default='baseline', max_length=20)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_indicators', to='pipeline.areaofinterest')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('aoi', 'date')},
            },
        ),
        migrations.CreateModel(
            name='OpticalAssetCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('asset_type', models.CharField(choices=[('aircraft', 'Aircraft'), ('vessel', 'Vessel')], max_length=20)),
                ('count', models.IntegerField(help_text='Number of bright objects detected')),
                ('baseline_count', models.FloatField(blank=True, help_text='Pre-war average count for this AOI', null=True)),
                ('pct_change', models.FloatField(blank=True, help_text='Percentage change vs baseline', null=True)),
                ('cloud_fraction', models.FloatField(default=0, help_text='Fraction of AOI obscured by cloud (0–1)')),
                ('scene_id', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(default='Sentinel-2', help_text='e.g. Sentinel-2, SkyFi', max_length=50)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optical_asset_counts', to='pipeline.areaofinterest')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('aoi', 'date', 'asset_type', 'source')},
            },
        ),
    ]
