# Generated by Django 5.2 on 2026-03-10 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_alter_areaofinterest_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_icao', models.CharField(help_text='ICAO airport code', max_length=4)),
                ('airport_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('arrivals', models.IntegerField(default=0)),
                ('departures', models.IntegerField(default=0)),
                ('total_movements', models.IntegerField(default=0)),
                ('baseline_movements', models.FloatField(blank=True, help_text='Pre-war daily average movements', null=True)),
                ('pct_change', models.FloatField(blank=True, help_text='Percentage change vs baseline', null=True)),
                ('country', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('airport_icao', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GDELTEventCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('power_outage', models.IntegerField(default=0)),
                ('water_shortage', models.IntegerField(default=0)),
                ('fuel_shortage', models.IntegerField(default=0)),
                ('food_shortage', models.IntegerField(default=0)),
                ('protest', models.IntegerField(default=0)),
                ('refugee', models.IntegerField(default=0)),
                ('infrastructure_damage', models.IntegerField(default=0)),
                ('economic_impact', models.IntegerField(default=0)),
                ('total_crisis_events', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('country', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GroundwaterAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('month', models.DateField(help_text='First day of the month')),
                ('mean_ewt_cm', models.FloatField(help_text='Mean equivalent water thickness anomaly in cm')),
                ('baseline_ewt_cm', models.FloatField(blank=True, help_text='Long-term average EWT for this month', null=True)),
                ('anomaly_cm', models.FloatField(blank=True, help_text='Deviation from baseline in cm', null=True)),
                ('min_ewt_cm', models.FloatField(blank=True, null=True)),
                ('max_ewt_cm', models.FloatField(blank=True, null=True)),
                ('pixel_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('region_name', 'month')},
            },
        ),
        migrations.CreateModel(
            name='InternetOutage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('ioda_bgp', models.FloatField(blank=True, help_text='IODA BGP visibility level (0–1)', null=True)),
                ('ioda_active_probing', models.FloatField(blank=True, help_text='IODA active probing reachability (0–1)', null=True)),
                ('cloudflare_traffic', models.FloatField(blank=True, help_text='Cloudflare HTTP traffic index (0–1)', null=True)),
                ('overall_connectivity', models.FloatField(help_text='Combined connectivity score (0=offline, 1=normal)')),
                ('baseline_connectivity', models.FloatField(blank=True, help_text='Pre-war average connectivity', null=True)),
                ('pct_change', models.FloatField(blank=True, help_text='Percentage change vs baseline', null=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('country', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NO2Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mean_no2', models.FloatField(help_text='Mean tropospheric NO2 in µmol/m²')),
                ('median_no2', models.FloatField(blank=True, help_text='Median tropospheric NO2 in µmol/m²', null=True)),
                ('baseline_no2', models.FloatField(blank=True, help_text='Pre-war average NO2 in µmol/m²', null=True)),
                ('pct_change', models.FloatField(blank=True, help_text='Percentage change vs baseline', null=True)),
                ('pixel_count', models.IntegerField(default=0, help_text='Valid pixels in AOI')),
                ('cloud_fraction', models.FloatField(default=0, help_text='Fraction of AOI with low QA (0–1)')),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no2_readings', to='pipeline.areaofinterest')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('aoi', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SARCoherenceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_date', models.DateField(help_text='Pre-war scene date')),
                ('post_date', models.DateField(help_text='Post-war scene date')),
                ('mean_correlation', models.FloatField(help_text='Mean intensity correlation (0=destroyed, 1=unchanged)')),
                ('low_correlation_fraction', models.FloatField(help_text='Fraction of area with correlation < 0.3')),
                ('change_area_km2', models.FloatField(default=0, help_text='Estimated area of significant change in km²')),
                ('pixel_count', models.IntegerField(default=0)),
                ('pre_scene_id', models.CharField(blank=True, default='', max_length=200)),
                ('post_scene_id', models.CharField(blank=True, default='', max_length=200)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sar_coherence_changes', to='pipeline.areaofinterest')),
            ],
            options={
                'ordering': ['-post_date'],
                'unique_together': {('aoi', 'pre_date', 'post_date')},
            },
        ),
        migrations.CreateModel(
            name='ThermalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('signature_present', models.BooleanField(help_text='Whether expected thermal signature was detected')),
                ('max_frp', models.FloatField(blank=True, help_text='Maximum FRP within detection radius (MW)', null=True)),
                ('fire_count', models.IntegerField(default=0, help_text='Number of thermal detections within radius')),
                ('baseline_fire_count', models.FloatField(blank=True, help_text='Pre-war average daily fire count', null=True)),
                ('status', models.CharField(choices=[('operating', 'Operating'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermal_signatures', to='pipeline.areaofinterest')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('aoi', 'date')},
            },
        ),
    ]
