# Generated by Django 5.2 on 2026-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_flightactivity_gdelteventcount_groundwateranomaly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalsignature',
            name='damage_detected',
            field=models.BooleanField(default=False, help_text='True if fire pattern indicates strike/damage (not normal operations)'),
        ),
        migrations.AddField(
            model_name='thermalsignature',
            name='facility_profile',
            field=models.CharField(choices=[('flaring', 'Flaring (oil/refinery/LNG — fires expected when operating)'), ('non_flaring', 'Non-flaring (desal/power — fires indicate damage)')], default='non_flaring', help_text='Determines interpretation: flaring=fires normal, non_flaring=fires abnormal', max_length=20),
        ),
        migrations.AlterField(
            model_name='thermalsignature',
            name='status',
            field=models.CharField(choices=[('operating', 'Operating'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('damaged', 'Damaged'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
