# Generated by Django 5.2 on 2026-03-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_thermalsignature_damage_detected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NZFuelSecurityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('hormuz_disruption', models.FloatField(default=0, help_text='Hormuz SAR disruption score (0-1)')),
                ('price_acceleration', models.FloatField(default=0, help_text='Fuel price acceleration score (0-1)')),
                ('stock_depletion', models.FloatField(default=0, help_text='Stock depletion score (0-1)')),
                ('supply_chain', models.FloatField(default=0, help_text='Supply chain disruption score (0-1)')),
                ('demand_signal', models.FloatField(default=0, help_text='Demand signal score (0-1)')),
                ('gdelt_narrative', models.FloatField(default=0, help_text='GDELT fuel_shortage narrative score (0-1)')),
                ('fuel_security_risk', models.FloatField(default=0, help_text='Weighted composite risk (0-1)')),
                ('security_level', models.CharField(choices=[('normal', 'Normal'), ('watch', 'Watch'), ('warning', 'Warning'), ('critical', 'Critical'), ('rationing', 'Rationing')], default='normal', max_length=20)),
                ('estimated_days_to_mso', models.FloatField(blank=True, help_text='Estimated days until worst fuel type hits MSO minimum', null=True)),
                ('estimated_rationing_date', models.DateField(blank=True, help_text='Projected date rationing begins', null=True)),
                ('depletion_projections', models.JSONField(blank=True, default=dict, help_text='Per-fuel-type depletion model outputs')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FuelPriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fuel_type', models.CharField(choices=[('91', 'Regular Petrol 91'), ('95', 'Premium Petrol 95'), ('diesel', 'Diesel')], max_length=10)),
                ('retail_price_nzd', models.FloatField(help_text='Retail price NZD/litre')),
                ('import_cost_nzd', models.FloatField(blank=True, help_text='Import cost NZD/litre', null=True)),
                ('margin_nzd', models.FloatField(blank=True, help_text='Margin NZD/litre', null=True)),
                ('baseline_price', models.FloatField(blank=True, help_text='Pre-war average price NZD/litre', null=True)),
                ('pct_change', models.FloatField(blank=True, help_text='Percentage change vs baseline', null=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'fuel_type')},
            },
        ),
        migrations.CreateModel(
            name='FuelStockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('jet', 'Jet Fuel')], max_length=10)),
                ('stock_type', models.CharField(choices=[('onshore', 'Onshore'), ('on_water', 'On Water'), ('total', 'Total')], max_length=10)),
                ('days_of_supply', models.FloatField(help_text='Days of supply at current consumption')),
                ('volume_ml', models.FloatField(blank=True, help_text='Volume in megalitres', null=True)),
                ('mso_minimum_days', models.FloatField(blank=True, help_text='Minimum Stock Obligation minimum days', null=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'fuel_type', 'stock_type')},
            },
        ),
    ]
